### ISSUE TITLE
Results.js and other js files are initialized multiple times, running each function more than the once it is needed.

### ISSUE THREAD

**Issue by JoshEKruse-zz** [stevenenriquez/intellichirp-snaw#11]
Makes website slower and less responsive. 
A statement is used to allow the functions in Results.js to not be ran when the page is updated but they are still ran multiple times as Results.js is initialized multiple times.

**Comment by JoshEKruse-zz** [comment]
Run classification and spectrogram image functions only when the ANALYZE button is clicked

**Comment by BigNasty000** [comment]
I've got this issue slightly solved in Development-Mike. 
Results.js and api.py contain functions which check if the upload folder has anything in it. If it doesn't, then the spectro/classification functions will not run. But currently the functions will run when the "Submit" button is hit, not the analyze button.

**Comment by BigNasty000** [comment]
Bug has been fixed, and a new issue has spawned. Results.js classification runs when files are uploaded via the "submit" button, instead of the "analyze" button.
