### ISSUE TITLE
Create offline script that runs a classification on every audio file in a server

### ISSUE THREAD

**Issue by JoshEKruse-zz** [stevenenriquez/intellichirp-snaw#21]

**Comment by JoshEKruse-zz** [comment]
- Points to directory
- Loops on every file in dir
- Outputs to CSV

**Comment by JoshEKruse-zz** [comment]
3 parameters, upload folder, output folder, f flag for single file, d flag for directory

**Comment by stevenenriquez** [comment]
Completed by Josh in branch 'standalone'
