### ISSUE TITLE
Export function is broken with change to how the dictionary is passed to results.js

### ISSUE THREAD

**Issue by JoshEKruse-zz** [stevenenriquez/intellichirp-snaw#31]

**Comment by BigNasty000** [comment]
How are we planning to display the exported file in CSV?

**Comment by JoshEKruse-zz** [comment]
honestly not sure. maybe we can use whatever code zhenyu creates for the standalone. write a smaller py script that creates a csv. then export that to the user

**Comment by BigNasty000** [comment]
Export working properly.
- Need CSV export instead of txt
- Pretty print to CSV
