### ISSUE TITLE
Classification.py needs to return a created JSON dictionary based off of classification

### ISSUE THREAD

**Issue by JoshEKruse-zz** [stevenenriquez/intellichirp-snaw#6]

**Comment by BigNasty000** [comment]
Why does classification need to return a JSON Dictionary? 

Was able to just send a Dictionary to the Results.js and is read and displayed properly on the line chart.
Done in Development-Mike

**Comment by JoshEKruse-zz** [comment]
Classification.py successfully returns a dictionary to be used by the front-end. Was not implemented as a JSON object as originally thought of but code works fine. 

#31 Issue was created as the export function is now broken but further work was needed on that anyways.
